# Application Name
spring.application.name=multivendor-platform

# Server Port
server.port=${PORT:8080}

# LOCAL MySQL Database (default profile) / Overridden by GCP Cloud Run via Env Vars
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/multivendor_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ayush7697}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
